[IV-22-23] Objetivo 0
jmramirezG/WhatCook pull request #1
Opened 2022-09-16 15:48 UTC by jmramirezG

Primera revisión
* [ ] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [ ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

2022-09-18 08:08 UTC, jmramirezG commented
Añadidos README y licencia.

Documentación de cómo configurar git lista.

Solicito evaluación.

2022-09-18 16:09 UTC, JJ requested changes
Por favor, consulta el concepto de lógica de negocio y qué es aceptable. Trata de hacer correctamente en proceso de *design thinking* para empatizar con los posibles clientes y localizar el problema.

2022-09-18 16:09 UTC, JJ commented on LICENSE
> +WhatCook
Esto es la cabecera que tendrías que incluir en cada fichero, no el fichero completo. Por favor, incluye el fichero completo.

2022-09-18 16:09 UTC, JJ commented on README.md
> +También está el **problema económico**: ¿dónde compro para que el precio sea el menor posible?
Cuanto introduces un "también" es que el problema del que estás hablando no está claro. Un problema tiene que ser algo claro y directo.

2022-09-18 17:22 UTC, jmramirezG commented
> Por favor, consulta el concepto de lógica de negocio y qué es aceptable. Trata de hacer correctamente en proceso de _design thinking_ para empatizar con los posibles clientes y localizar el problema.

Con añadir la sintetización del problema y el flujo de datos del sistema, viendo así cómo se realizaría la solución un poco más en detalle y observando el problema de forma lo más clara posible, sin tanto lenguaje coloquial, creo que quedaría resuelto.

> Esto es la cabecera que tendrías que incluir en cada fichero, no el fichero completo. Por favor, incluye el fichero completo.

Esto solucionado, he añadido el AGPL completo y referenciado en los archivos de texto el contrato completo. Está referenciado al final, se que se tiene que referenciar al principio, pero en archivos de texto que se vayan a leer con formato (markdown en este caso), creo que visualmente queda mejor así. En los archivos de código estará referenciado al comienzo.

> Cuanto introduces un "también" es que el problema del que estás hablando no está claro. Un problema tiene que ser algo claro y directo.

Esto solucionado también, he añadido la sintetización del problema para que quede claro qué estoy abordando.


Espero más feedback!

2022-09-19 10:59 UTC, JJ requested changes
parece que te estás acercando, pero
* El contexto no está claro. la información (y valor) que aporta el programa, por ejemplo
* La lógica de negocio no está claro que sea más que buscar (recetas con ingredientes, precios mínimos) (y tampoco está nada claro que los precios puedan salir de un ticket)
* La justificación para que sea una aplicación en la nube tampoco es aceptable.

2022-09-19 10:59 UTC, JJ commented on README.md
> +Se propone un sistema que ofrezca la posibilidad al usuario de que **introduzca los ingredientes disponibles** (bien mediante el escaneo de un ticket de compra o mediante la introducción manual de lo
No propongáis ninguna solución donde el usuario tenga que introducir cosas. Si tiene que introducir cosas, tarda menos en meterse en el frigo y mirar lo que hay. Empatizar con el usuario (parte del design thinking) incluye conocer al usuario y saber lo que está dispuesto a hacer y lo que no. Mira [aquí, en la siguiente sesión]8https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-02.md) los errores frecuentes, uno de los cuales es "que el usuario escriba cosas"

2022-09-19 10:59 UTC, JJ commented on README.md
> +En el caso de no poder hacer nada, le propondría **recetas para las que tuviera que comprar algún ingrediente**, los menos posibles.
¿Quién mete esas recetas?

2022-09-19 10:59 UTC, JJ commented on README.md
> +En este último caso, se podrían **usar los datos extraídos de los tickets** para sugerir al usuario dónde realizar la compra para que le salga **lo más barato posible**.
Sólo podrá comprar donde ya haya comprado, y sólo si está al mismo precio que en el ticket...

2022-09-19 10:59 UTC, JJ commented on README.md
> +* Calcula una o más recetas que se ajusten a los ingredientes proporcionados por el usuario.
¿Usando qué base de datos de recetas? ¿Cómo sabe los ingredientes que quedan?

2022-09-19 10:59 UTC, JJ commented on README.md
> +* Valida que la(s) receta(s) proporcionada(s) coincida(n) en la medida de lo posible con los ingredientes del usuario.
Sigue siendo nada más que búsqueda. Buscas las que tengan los ingredientes que tienes. Ya.

2022-09-19 10:59 UTC, JJ commented on README.md
> +* Calcula el precio aproximado de compra de los ingredientes restantes, en caso de tener suficientes datos para ello.
Y todo esto, ¿soluciona el problema?

2022-09-19 10:59 UTC, JJ commented on README.md
> +4. En el caso de faltar ingredientes, se hace comparativa de precio, indicando al usuario dónde le resultaría más barato comprar los ingredientes restantes para cada receta.
Lo que no veo es qué pintan las recetas en todo esto. Le dices qué quieres comprar, y te dice donde es más barato.

2022-09-19 10:59 UTC, JJ commented on README.md
> +Los principales **clientes** serían **usuarios ocasianales** que usarían la aplicación para obtener ideas sobre qué comida cocinar en un momento determinado.
typo

2022-09-19 10:59 UTC, JJ commented on README.md
> +El despliegue en la nube de una aplicación con estas características tiene las siguientes ventajas:
Agh, no. No me vendas la nube. Dime para qué tiene que subir un ticket a la nube alguien en vez de hacerlo todo en su móvil.

2022-09-19 14:54 UTC, jmramirezG commented on README.md
> +Se propone un sistema que ofrezca la posibilidad al usuario de que **introduzca los ingredientes disponibles** (bien mediante el escaneo de un ticket de compra o mediante la introducción manual de lo
Principalmente el problema se basa en que el usuario, pese a saber lo que tiene, no sabe qué cocinar por falta de creatividad o de conocimientos culinarios, algo que en mi experiencia pasa mucho.

Partiendo de esa base, el usuario tendría, como mínimo, que introducir una foto del ticket de compra más reciente, porque es necesario saber qué tenemos para poder ofrecer recetas en consecuencia.

2022-09-19 14:58 UTC, jmramirezG commented on README.md
> +En este último caso, se podrían **usar los datos extraídos de los tickets** para sugerir al usuario dónde realizar la compra para que le salga **lo más barato posible**.
La idea principal con esto sería tener un histórico de tickets, con supermercado, tienda, y precio por ingredientes, así se podría hacer al menos una aproximación a la baja del precio de una supuesta compra de ingredientes restantes.

Por ejemplo, digamos que necesitamos comprar cebolla, piñones y atún y sabemos el precio de los piñones y de la cebolla, que ambos suman unos 11 euros. Podríamos decirle al usuario que la compra en x supermercado (cercano a él) le saldría a +11 euros, ya que no tenemos datos sobre el atún.

2022-09-19 15:11 UTC, jmramirezG commented
He añadido un nuevo apartado de porqué este sistema en específico ha de estar en la nube, espero que así quede más claro! Es cierto que antes podría haber estado refiriéndome a cualquier aplicación :)

Respecto a las recetas disponibles, en principio tenía pensado buscar una base de datos estándar y centrarme en el procesado de la entrada del usuario y el procesado interno de la recuperación del histórico de tickets para ofrecerle al usuario un supermercado cercano a él que tenga el menor precio posible. Seguramente la base de datos que use la expanda con recetas propias o, si veo que le falta algún caso extremo, la completaré.

Aunque la idea inicial se centraba más en la introducción manual de los ingredientes por parte del usuario, creo que sale más rentable centrarse en implementar un buen ocr y que el usuario se limite a escanear el ticket con la cámara de su dispositivo. Mantendremos el cuadro de texto para la introducción manual, pero para el usuario será más cómodo escanear un ticket.
A su vez, creo que daremos la opción de poder eliminar ingredientes de la lista, ya que siempre será más cómodo escanear un ticket con 100 alimentos y borrar tres que introducir 97 a mano!!

Espero más feedback para la siguiente iteración del proyecto,
Muchas gracias!!

2022-09-19 15:27 UTC, JJ commented on README.md
> +Se propone un sistema que ofrezca la posibilidad al usuario de que **introduzca los ingredientes disponibles** (bien mediante el escaneo de un ticket de compra o mediante la introducción manual de lo
Vamos a ir a la fase de empatizar dentro de *design thinking*.
la persona va gastando un poquito de mantequilla, la mitad de los macarrones, y ha hecho las patatas fritas y ha guardado lo que queda en un táper. Nos ponemos en sus botas. ¿Qué va a hacer entonces con la aplicación? ¿Tú lo harías?

2022-09-19 15:31 UTC, JJ commented on README.md
> +En este último caso, se podrían **usar los datos extraídos de los tickets** para sugerir al usuario dónde realizar la compra para que le salga **lo más barato posible**.
Volvemos a empatizar. Muchas tiendas tienen sólo conceptos como "verduras" o "fruta". Los precios fluctúan dependiendo del suministro. Aplicar un algoritmo de predicción a esto no tiene sentido, ni va a solucionar ningún problema. 
Te lo digo porque yo voy a comprar la fruta casi todos los días, y es así. Por eso os dije que teníais que tener conocimiento personal.

2022-09-19 15:34 UTC, JJ commented
> He añadido un nuevo apartado de porqué este sistema en específico ha de estar en la nube, espero que así quede más claro! Es cierto que antes podría haber estado refiriéndome a cualquier aplicación :)
> 
> Respecto a las recetas disponibles, en principio tenía pensado buscar una base de datos estándar y centrarme en el procesado de la entrada del usuario y el procesado interno de la recuperación del histórico de tickets para ofrecerle al usuario un supermercado cercano a él que tenga el menor precio posible. Seguramente la base de datos que use la expanda con recetas propias o, si veo que le falta algún caso extremo, la completaré.
> 
> Aunque la idea inicial se centraba más en la introducción manual de los ingredientes por parte del usuario, creo que sale más rentable centrarse en implementar un buen ocr y que el usuario se limite a escanear el ticket con la cámara de su dispositivo. Mantendremos el cuadro de texto para la introducción manual, pero para el usuario será más cómodo escanear un ticket. A su vez, creo que daremos la opción de poder eliminar ingredientes de la lista, ya que siempre será más cómodo escanear un ticket con 100 alimentos y borrar tres que introducir 97 a mano!!
> 
> Espero más feedback para la siguiente iteración del proyecto, Muchas gracias!!

la lógica de negocio tienes que implementarla tú, porque tiene que ser código propio que tú testees. Incluso aunque lo hagas, un ticket escaneado no te da los datos en CSV. Tienes que extraer de ahí de qué tienda se trata y cada uno de los ingredientes. Eso es un problema en sí. Y aunque lo hagas, los tickets no te van a decir ni predecir el precio, porque no depende de la serie temporal. Y aunque lo hicieran, sólo te van a dar de las tiendas donde hayas estado.

¿De veras no quieres volver al proceso de design thinking y pensar en otro problema y otra solución?

2022-09-20 09:27 UTC, jmramirezG commented
> ¿De veras no quieres volver al proceso de design thinking y pensar en otro problema y otra solución?

He cambiado completamente el README, intentando otro problema que creo que se puede ajustar mejor a la naturaleza de la asignatura.

En resumen, control integral de las cuentas de una asociación/peña que hace sus fiestas y necesita saber qué socio consume qué.

2022-09-20 10:28 UTC, JJ requested changes
No se trata de que hagáis las cosas de nuevo desde cero, sino de que tratéis de entender los conceptos.

2022-09-20 10:28 UTC, JJ commented on README.md
> +* Gestión de las cuentas de la asociación/peña durante las barras o fiestas que organiza.
= almacenar y buscar

2022-09-20 10:28 UTC, JJ commented on README.md
> +* Registro de cúanto consume cada socio, ofreciendo estadísticas disponibles a la administración de la asociación/peña.
= operación trivial sobre lo almacenado, que además no resuelve el problema. En el contexto anterior no has dicho que lo que falten sean estadísticas.

2022-09-20 10:28 UTC, JJ commented on README.md
> +Se propone un sistema que ofrezca a una asociación o peña prescindir de los tickets y del dinero físico, asignando a cada socio una tarjeta (bien con un QR o RFID), en la que el socio podrá cargar di
Implementación física que no tiene nada que ver con la asignatura.

2022-09-20 10:28 UTC, JJ commented on README.md
> +El socio podrá recargar dinero, viéndose esto reflejado inmediatamente en el saldo de su tarjeta.
No hay ninguna lógica de negocio. "Recargar" es escribir. Por favor, revisa el concepto de la lógica de negocio y trata de reflejarlo en tu propuesta.

2022-09-20 10:50 UTC, jmramirezG commented
He cambiado un par de cosillas del modelo de negocio y del problema, a ver si así se aprecia mejor a lo que me refiero con el problema y la solución.

También he prescindido de hablar de implementación física.

2022-09-20 10:51 UTC, jmramirezG commented
Pequeño typo, listo para revisión

2022-09-20 10:54 UTC, JJ requested changes
Cambiarle el título no es entender el problema.

2022-09-20 11:34 UTC, jmramirezG commented
He orientado más el proyecto a la predicción basado en los datos que se poseen.

Seguirá actuando como aplicación de contabilidad, pero se le pueden solicitar informes y predicciones acerca de eventos futuros, cómo sería qué hay que comprar para esta barra y cúal es el beneficio esperado.

2022-09-20 17:12 UTC, jmramirezG commented
Solicito evaluación

2022-09-20 18:22 UTC, JJ requested changes
Tienes que llegar un momento en el que, por mucho que empatices con tu peña, concluyas que los problemas que tiene no son adecuados para esta asignatura. Puede ser para un TFM un proyecto personal, pero sin lógica de negocio y sin identificación clara de un problema, no te van a servir para desarrollar el proyecto.

2022-09-20 18:22 UTC, JJ commented on README.md
> +Estos problemas tienen una solución.
Espero que sea una sola solución, porque los problemas parecen muy diferentes. Todos los problemas que mencionas son problemas físicos y vas a tener los mismos en un programa. La gente no tecleará los tickets, no dirá cuando sale algo del almacén... Trabajar con un problema físico es interesante, pero no algo que sirva para esta asignatura

2022-09-20 18:22 UTC, JJ commented on README.md
> +  * Calculará los productos faltantes para que la fiesta se desarrolle con normalidad.
Esto es una resta. No hay ninguna lógica de negocio complicada.

2022-09-20 18:46 UTC, jmramirezG commented
El grueso del problema se encuentra en predecir los datos para la próxima fiesta en función del inventario y las fiestas anteriores.

Si nos vamos a la diapositivas de [design thinking](https://jj.github.io/IV/preso/design-thinking.html#/3/1/0) se puede ver como ejemplo de aplicación precisamente una que realiza eso a lo que me refiero.

El problema, como viene expresado, contiene preparación de las futuras fiestas. Si, es un problema de muchos, pero la solución que propongo es una solución integral, estando la parte de procesado centrada en esta predicción y siendo el resto de la solución un soporte para hacerla posible.

Espero su respuesta

2022-09-20 18:58 UTC, JJ commented
> El grueso del problema se encuentra en predecir los datos para la próxima fiesta en función del inventario y las fiestas anteriores.

Eso no es el grueso del problema. Para empezar, ni es un problema. ¿En serio que no sabe la peña cuanto comprar para la siguiente fiesta? 
> 
> Si nos vamos a la diapositivas de [design thinking](https://jj.github.io/IV/preso/design-thinking.html#/3/1/0) se puede ver como ejemplo de aplicación precisamente una que realiza eso a lo que me refiero.

Pero en nuestro caso, usábamos los datos de todos los agricultores que estaban en la aplicación y, al principio, los datos de las lonjas. Esos datos son públicos y el agricultor puede beneficiarse de ellos incluso aunque no haya introducido nada (al principio del uso del programa).

Además, pensábamos usar análisis estadísticos que tuvieran en cuenta estacionalidad y demás, usando bibliotecas ya publicadas. Vosotros no podéis usar bibliotecas publicadas, porque tenéis que programar la lógica de negocio usando las historias de usuario. Por eso, predecir es complicado. Si se puede hacer un ajuste por mínimos cuadrados y una proyección, bien (siempre que se tengan los datos, claro, que es algo imprescindible y que tú no tienes). En general, no van a valer para esta asignatura.
> 
> El problema, como viene expresado, contiene preparación de las futuras fiestas. Si, es un problema de muchos, pero la solución que propongo es una solución integral, estando la parte de procesado centrada en esta predicción y siendo el resto de la solución un soporte para hacerla posible.

No, no es un problema, porque no estás formulando ningún problema. Ponle "ojalá" a ver si funciona. "Ojalá que pudiera saber cuanto va a consumir la gente en la fiesta siguiente". No, porque a) no lo sabes b) ya se apañará la gente para comprar lo que buenamente entienda y c) aunque lo supieras no tienes datos para entrenar un modelo ni un algoritmos simple que puedas programar tú.

2022-09-21 11:21 UTC, jmramirezG commented
Nuevo problema expresado, creo que más afín a lo que se pide para la asignatura!

Solicito revisión cuando sea posible

2022-09-22 09:08 UTC, jmramirezG commented
Gracias por el comentario!

En cuanto siga con el siguiente objetivo tendré ya una arquitectura y el procesamiento planteados de forma que efectivamente se beneficie de estar desplegado en nube.

Le hago el merge al PR!

2022-09-22 09:11 UTC, merged