[IV-22-23] Objetivo 3
jmramirezG/WhatCook pull request #13
Opened 2022-11-13 18:17 UTC by jmramirezG

* [X] ¿Incluye el fichero iv.yaml las claves de todos los objetivos anteriores?
* [X] ¿Se ha desarrollado el fichero para las tareas a partir de un issue?
* [X] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la existencia de herramientas que permitan automatizar tareas?
* [X] ¿Hemos justificado correctamente en caso de elegir un gestor de dependencias el que se use como gestor de tareas?
* [X] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [X] ¿La tarea check efectivamente comprueba la sintaxis de los fuentes existentes y sólo eso?

2022-11-14 08:59 UTC, JJ requested changes
No me anuncies lo que eliges, dime los criterios que sigues y por qué. Lee por favor errores frecuentes de la semana 8 a la 10.

2022-11-14 08:59 UTC, JJ commented on README.md
> +  go build && ./<nombreejecutable>
EStás usando go como task manager entonces.

2022-11-14 08:59 UTC, JJ commented on docs/gestor-tareas.md
> +Como gestor de tareas hemos elegido [Task](https://taskfile.dev/), como hemos comentado en el issue #11.
Tienes que establecer los criterios, mostrar las opciones, y luego elegir.

2022-11-14 08:59 UTC, JJ commented on docs/gestor_dependencia.md
> +Como gestor de dependencias hemos elegido [Go Modules](https://go.dev/blog/using-go-modules), como hemos comentado en el issue #12.
Ídem

2022-11-14 18:06 UTC, jmramirezG commented on README.md
> +  go build && ./<nombreejecutable>
No, como task manager estamos usando [Task](https://taskfile.dev/), no obstante aún no hemos implementado las tareas de hacer build y ejecutar en el mismo. Debería añadirla?

2022-11-14 18:08 UTC, JJ commented on README.md
> +  go build && ./<nombreejecutable>
¿para qué sirve el task manager entonces?

2022-11-14 18:18 UTC, jmramirezG commented on README.md
> +  go build && ./<nombreejecutable>
El task manager de momento tan solo checkea la sintaxis de los archivos disponibles, mediante el uso del comando ```task check```.

Eventualmente se ampliará su uso para construir y lanzar el proyecto, pero como se especifica en los requisitos del objetivo tres, de momento solo era necesario que checkeara la sintaxis.

No obstante, puedo ampliarlo para que haga build y lance el proyecto.

2022-11-14 18:22 UTC, jmramirezG commented on README.md
> +  go build && ./<nombreejecutable>
Perfecto entonces!

2022-11-14 18:30 UTC, jmramirezG commented on docs/gestor-tareas.md
> +Como gestor de tareas hemos elegido [Task](https://taskfile.dev/), como hemos comentado en el issue #11.
Actualizado razonamiento

2022-11-14 18:30 UTC, jmramirezG commented on docs/gestor_dependencia.md
> +Como gestor de dependencias hemos elegido [Go Modules](https://go.dev/blog/using-go-modules), como hemos comentado en el issue #12.
Actualizado razonamiento

2022-11-14 22:55 UTC, jmramirezG commented on README.md
> +  go build && ./<nombreejecutable>
Arreglado, ya usamos task para todo!

2022-11-14 22:56 UTC, jmramirezG reviewed
Cambios realizados, solicito evaluación @JJ

2022-11-15 06:31 UTC, JJ approved these changes
Voy a aceptar, aunque ni es completa la lista de gestores de tareas ni original, ya es casualidad que hayas elegido el mismo que otro estudiante de la clase.

2022-11-15 06:31 UTC, JJ commented on docs/gestor-tareas.md
> +Vamos a considerar los 3 siguientes gestores de tareas:
¿Por qué sólo esos 3? ¿Por qué excluyes `make`, por ejemplo?

2022-11-15 06:31 UTC, JJ commented on docs/gestor-tareas.md
> +[Gilbert](https://github.com/go-gilbert/gilbert) es un gestor de tareas estilo ```Graden``` y ```Maven```, buscando una sintaxis declarativa.
¿Qué es `graden`?

2022-11-15 06:31 UTC, JJ commented on docs/gestor-tareas.md
> +[Realize](https://github.com/oxequa/realize) ofrece una doble función de *live reload* y gestor de tareas.
¿Qué relevancia tiene esa función y qué tiene que ver con los tres criterios?

2022-11-15 06:31 UTC, JJ commented on docs/old_README.md
> +# WhatCook
No metáis en estos PRs cosas que no son relevantes para el mismo.

2022-11-15 06:31 UTC, JJ commented on internal/documento.go
> +/*
Igual, irrelevante para este PR.

2022-11-15 17:23 UTC, jmramirezG commented on docs/gestor-tareas.md
> +[Gilbert](https://github.com/go-gilbert/gilbert) es un gestor de tareas estilo ```Graden``` y ```Maven```, buscando una sintaxis declarativa.
Es un typo, es [Gradle}(https://gradle.org/). Estaba ya leyendo Maven y debí de confundirme y no darme cuenta.

2022-11-15 17:24 UTC, jmramirezG commented on docs/gestor-tareas.md
> +[Realize](https://github.com/oxequa/realize) ofrece una doble función de *live reload* y gestor de tareas.
Realmente con los criterios no tiene nada que ver, si es cierto que para el resto del desarrollo del proyecto puede ser muy útil, no obstante, al estar tan desactualizado, prefiero evitar usar *Realize*.

2022-11-15 17:31 UTC, jmramirezG commented on docs/gestor-tareas.md
> +Vamos a considerar los 3 siguientes gestores de tareas:
Busqué gestores de tareas que estuvieran especialmente pensados para Go, es por ello que excluyo ```make``` de la lista, ya que no está explicitamente pensado para Go.

Al final acabé escogiendo Task simplemente por la simpleza de uso e instalación, además, el proceso que seguí fue buscar [task runner for go](https://duckduckgo.com/?q=task+runner+for+go&t=newext&atb=v346-1&ia=web) en *duckduckgo*, accedí a la [búsqueda de github](https://github.com/topics/task-runner?l=go) que aparece como cuarta opción y desde ahí Task aparece en segundo lugar nombrando que intenta ser más sencillo que ```make``` con la descripción de *A task runner / simpler Make alternative written in Go*.

2022-11-15 17:32 UTC, merged