[IV-22-23] Objetivo 2. Inicialización del proyecto y primer PMV
jmramirezG/WhatCook pull request #9
Opened 2022-10-03 15:34 UTC by delightfulagony

Sobre la estructura del repositorio

 - [ ] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y disposición de los mismos?

Sobre el análisis del problema

 - [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo que se ha creado?
 - [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor, una entidad o un agregado?
 - [ ] ¿He propuesto un producto mínimamente viable, que en general será un solo objeto valor que no dependa de ningún otro (y que sea la base de muchos otros)?.

Sobre la planificación y la programación

 - [x] ¿Los issues representan un problema, y no una tarea?
 - [ ] ¿Todos los mensajes de commit explican el cambio, y no se limitan a repetir el nombre del fichero que se ha cambiado?
 - [ ] ¿Los mensajes de commit siguen el [el formato estándar y las buenas prácticas](https://www.theserverside.com/video/Follow-these-git-commit-message-guidelines).
 - [ ] ¿Se ha hecho una revisión real del código para comprobar que todos los atributos y funciones creadas están respaldadas por una HU?
 - [ ] ¿Todos los issues creados están asignados a una HU?
 - [ ] ¿Todos los cambios en el código están asignados a un issue?
 - [ ] Los issues sobre los que estoy trabajando, ¿han sido asignados al primer milestone?
 - [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
 - [ ] ¿Son los milestones sobre los que estoy trabajando productos mínimamente viables? ¿O tengo que solicitar al product manager que cree milestones adicionales o precise de qué producto se trata?

2022-10-04 11:00 UTC, delightfulagony commented
@jmramirezG mira a ver qué te parece, también si puedes asignar el milestone correspondiente a este PR estaría genial, que yo no puedo

2022-10-04 11:04 UTC, jmramirezG commented
Asignado!

Te importa si le echo el ojo mañana por la mañana?

2022-10-05 15:41 UTC, delightfulagony commented
¿Se lo enviamos a JJ que le eche un ojo?

2022-10-06 17:04 UTC, jmramirezG commented
Adelante!

Se lo tengo que mandar yo o se lo mandas tú? Que esto del objetivo 2 no sé muy bien cómo va jaja

2022-10-06 19:46 UTC, delightfulagony commented
Se lo tengo que mandar yo, ahora mismo estoy desde el móvil pero de mañana no pasa 💪

2022-10-26 10:18 UTC, jmramirezG approved these changes

2022-10-26 10:19 UTC, jmramirezG commented
Solicitamos revisión @JJ

2022-10-26 10:35 UTC, JJ requested changes
Por favor, echadle un vistazo a los comentarios. Lo esencial en este objetivo es que se siga una metodología de desarrollo ágil y eficiente, y para eso es imprescindible desarrollar según issues e historias de usuario.

2022-10-26 10:35 UTC, JJ commented on documento.go
> +	// Create a TemplateDocument object from an input office file.
En este objetivo no se pedía ninguna lógica de negocio.

2022-10-26 10:35 UTC, JJ commented on cliente.go
> +package WhatCook
No se siguen las buenas prácticas en situación del fichero (consultar [esto](https://github.com/golang-standards/project-layout))

2022-10-26 10:35 UTC, JJ commented on go.sum
> +github.com/PDFTron/pdftron-go v1.1.0 h1:FInPWDb4TvZYi1j34OmvZvbntOYura2Wlf2oFrEIiTg=
El milestone debe presentar un producto mínimo. No creo que pida nada de dependencias.

2022-10-26 10:35 UTC, JJ commented on cliente.go
> +type Cliente struct {
¿De qué forma esto corresponde a un modelo del problema? En el mensaje de commit no se hae ninguna referencia a un issue.

2022-10-26 13:48 UTC, delightfulagony commented on cliente.go
> +type Cliente struct {
El mensaje de commit referencia la issue #8:

> Implementa la estructura Cliente
> De acuerdo con lo discutido en https://github.com/jmramirezG/WhatCook/issues/8, se implementa
> la estructura de datos de Cliente representando los
> datos necesarios para la aplicación.
> Closes https://github.com/jmramirezG/WhatCook/issues/8

¿Debería referenciar también la historia de usuario a la que hace referencia?

2022-10-26 14:09 UTC, JJ commented on cliente.go
> +type Cliente struct {
Generalmente es una buena práctica referenciar el issue en la primera línea, y debería ser informativo sobre qué solución propone. No hace falta referenciar la HU, salvo que sea necesario para explicar la solución.

2022-10-26 15:00 UTC, delightfulagony commented on cliente.go
> +type Cliente struct {
¡De acuerdo! ¿Le hago un amend al commit?

2022-10-26 15:16 UTC, delightfulagony commented on cliente.go
> +type Cliente struct {
¿Nuevos commits a ese mismo archivo o añado nuevos commits en general?
Si es lo segundo lo he hecho en 1008844. 
Si es lo primero, ¿necesito cambiar algo o hay alguna forma de hacerlo sin modificar el archivo?

2022-10-26 17:25 UTC, JJ commented on cliente.go
> +type Cliente struct {
Bueno, donde tengas que hacer cambios... No, no se puede hacer sin modificar el archivo.

2022-10-27 06:45 UTC, delightfulagony commented
Creo que ya he hecho todos los cambios @JJ

2022-10-27 06:59 UTC, JJ approved these changes
Lo voy a dar por bueno, pero la historia de usuario #3 tiene que estar asignada a este milestone.

2022-10-27 08:40 UTC, jmramirezG commented
Asignada!

Hago el merge

2022-10-27 08:41 UTC, merged